# This is a basic workflow to help you get started with Actions

name: Verify

# Controls when the action will run.
on:
  push:
  pull_request:
    branches: [main, develop, test]

  workflow_dispatch:
    inputs:
      name:
        description: "Reason for dispatch"
        required: true
        default: "Just running some tests"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.17.0
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
        
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        run: |
          bin/rails db:setup

      - name: Run tests
        run: bin/rails test
